#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 28 11:03:27 2021

@author: akshat
"""

import tensorflow as tf

print(tf.__version__)


!tf_upgrade_v2 --infile networks_stylegan.py --outfile networks_stylganup.py --reportfile tree_report.txt# 